- instance_name: fjord
  instance_data_root: data/fjord
  instance_prompt: "a picture of [critrole-fjord], a male half-orc warlock"
  instance_urls:
  - "https://static.wikia.nocookie.net/criticalrole/images/8/80/Fjord_Level_20_portrait_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/3/36/Fjord_Level_17_portrait_-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/5/50/Fjord_Winter_Headshot.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/90/Fjordportrait2019.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/2/24/Fjord.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/c/c3/Fjord_Official_byArianaOrner.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/6/61/Fjord_by_Ariana_Orner.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/ff/Fjord_Winter.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/2/2b/Fjord_Level_20_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/8/82/Rammaru_Fjord.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/9b/Fjord_-_Stephanie_Brown.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/8/86/Fjord_underwater_-_Linda_Lith%C3%A9n.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/f4/Fjord_-_Linda_Lithen.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/e/ee/Fjord_with_Star_Razor_-_heartofpack.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/1/1d/Fjord_-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/0b/Fjord_and_Melora.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/ab/Fjord_star_razor_battletailors.jpeg"
  - "https://static.wikia.nocookie.net/criticalrole/images/4/4f/Fjord_with_the_Cloven_Crystal_-_Dan_Bittencourt.jpg"
  validation_prompt: "a picture of [critrole-fjord], a male half-orc warlock. background is a forest. fantasy art style, high quality, highly detailed, sharp focus"
- instance_name: beau
  instance_data_root: data/beau
  instance_prompt: "a picture of [critrole-beau], a female human monk"
  instance_urls:
  - "https://static.wikia.nocookie.net/criticalrole/images/a/a8/Beau_Level_20_portrait_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/e/e3/Beau_Level_17_portrait_-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/b/bd/Beauregard_Winter_Headshot.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/c/c8/Beauportrait2019.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/3/3e/Beauregard.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/5/59/Beauregard_Official_byArianaOrner.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/fe/Beauregard_by_Ariana_Orner.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/4/43/Beauregard_Winter.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/1/10/Beau_Level_20_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/3/3d/Beau_-_Elliott.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/a9/Beau_-_Ameera.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/5/59/Beau_heartofpack.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/a1/Beau_with_the_Goggles_-_Sally_Grew.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/b/b5/Beau_astral_sea.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/b/b5/Beau%27s_poem_-_Erin_A_Gray.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/9c/Beau_-_Scout_Villegas.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/7/7e/Beau_-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/d/db/Beau_-_Jenny_Tan.jpg"
  validation_prompt: "a picture of [critrole-beau], a female human monk. background is a forest. fantasy art style, high quality, highly detailed, sharp focus"
- instance_name: caduceus
  instance_data_root: data/caduceus
  instance_prompt: "a picture of [critrole-caduceus], a male firbolg cleric"
  instance_urls:
  - "https://static.wikia.nocookie.net/criticalrole/images/5/51/Caduceus_Level_20_portrait_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/6/6d/Caduceus_Winter_Headshot.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/b/b1/Cadportrait2019.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/7/78/Caduceus_portrait.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/03/Caduceus_Clay2.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/6/64/Caduceus_by_Ariana_Orner.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/4/4f/Caduceus_Winter.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/a3/Caduceus_Level_20_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/2/23/Caduceus_-_Sam_Hogg.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/3/33/Caduceus_-_Nikki_Dawes.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/2/2e/Caduceus_megzilla.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/2/2b/We%27re_running._It%27s_bad._Ravennowithtea.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/fb/Caduceus_Linda_Lithen.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/0a/Caduceus_Jessketchin.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/b/be/Caduceus_Casting_Spirit_Guardians_-_Josh_Ketchen.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/5/53/Caduceus_casting_Commune_by_Nikki_Dawes.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/1/1f/Caduceus_zroem.jpeg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/94/Cad_minttu.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/a0/Cad_offbeatworlds.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/98/IMG_20180728_114227.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/a8/Caduceus_-_Elimnebe.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/6/67/IMG_20180729_114524.jpg"
  validation_prompt: "a picture of [critrole-caduceus], a male firbolg cleric. background is a forest. fantasy art style, high quality, highly detailed, sharp focus"
- instance_name: caleb
  instance_data_root: data/caleb
  instance_prompt: "a picture of [critrole-caleb], a male human wizard"
  instance_urls:
  - "https://static.wikia.nocookie.net/criticalrole/images/d/d3/Caleb_Level_20_portrait_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/0a/Caleb_Level_17_portrait_-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/e/ef/Caleb_Winter_Headshot.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/1/15/Calebportrait2019.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/92/Caleb_Widogast.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/8/8f/Caleb_Official_byArianaOrner.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/2/2f/Caleb_by_Ariana_Orner.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/4/49/WinterM92Caleb-ArianaOrner.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/1/14/Caleb_-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/9c/Caleb_Level_20_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/05/Caleb_-_Linda_Lith%C3%A9n.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/4/49/Caleb_GalacticJonah.jpeg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/a8/C2E13_Caleb_beacon.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/3/31/Tyrone-Andersen-Caleb-Shield.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/7/72/Caleb_ranmaru.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/9a/Caleb_casting_fire_on_a_ship_-_Matt_Hubel.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/f7/Caleb_-_Old_Memories_Still_Burn_-_Nikki_Dawes.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/c/cd/Widogast%27s_Web_of_Fire_battletailors.jpeg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/ac/Caleb_and_Frumpkin_-_Minttu_Hynninen.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/5/52/Caleb_heartofpack.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/8/83/Caleb_welcoming_the_party_to_his_Tower_-_Cha_Cha_Rae.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/4/4b/Caleb_and_Frumpkin_hollyoakhill.jpeg"
  - "https://static.wikia.nocookie.net/criticalrole/images/1/1e/C2E6_CalebFrumpkin.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/c/c5/Caleb_eye_minttu.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/7/74/Caleb_casting_Haste_-_Giulia_Valentini_%28kurocyou%29.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/b/b3/Widogast%27s_Web_of_Fire_-_Linda_Lithen.jpg"
  validation_prompt: "a picture of [critrole-caleb], a male human wizard. background is a forest. fantasy art style, high quality, highly detailed, sharp focus"
- instance_name: jester
  instance_data_root: data/jester
  instance_prompt: "a picture of [critrole-jester], a female tiefling cleric"
  instance_urls:
  - "https://static.wikia.nocookie.net/criticalrole/images/0/09/Jester_level_20_portrait_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/c/cd/Jester_Level_17_portrait_-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/5/5d/Jester_Winter_Headshot.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/05/Jesterportrait2019.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/1/1b/Jester.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/7/7d/Jester_Official_byArianaOrner.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/0f/M9jesterfinal2.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/7/79/Jester_Winter.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/a3/Jester_level_20_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/8/83/Jester_lornart.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/91/Jester_-_Alartriss.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/ac/Jester_-_Linda_Lith%C3%A9n.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/08/Jester_as_High_Priestess_-_Porzio_Art.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/9f/Eleonora_Nascimbeni_-_Jester%27s_tarot_reading.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/2/2b/Captain_Jester.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/7/70/Jester_-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/c/ce/Jester_casting_%27%27Turn_Undead%27%27_-_Porzio_art.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/c/cf/Jester_casting_sashthesloth.jpeg"
  - "https://static.wikia.nocookie.net/criticalrole/images/6/66/Jester_casting_%27%27Inflict_Wounds%27%27_-_Dian_Huynh.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/e/e7/Jester_Spiritual_Weapon.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/4/4f/Jester_and_the_bees_-_FurballTsarina.jpg"
  validation_prompt: "a picture of [critrole-jester], a female tiefling cleric. background is a forest. fantasy art style, high quality, highly detailed, sharp focus"
- instance_name: nott
  instance_data_root: data/nott
  instance_prompt: "a picture of [critrole-nott], a female goblin rogue"
  instance_urls:
  - "https://static.wikia.nocookie.net/criticalrole/images/b/b2/M9nottfinal2Headshot.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/d/dc/Nott.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/b/b1/Nott_Official_byArianaOrner.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/b/b8/Nott_the_Brave_by_Ariana_Orner.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/5/5e/Nott_by_Mintscribbleart.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/a8/Nott_-_Monica_Magana.jpg"
  validation_prompt: "a picture of [critrole-nott], a female goblin rogue. background is a forest. fantasy art style, high quality, highly detailed, sharp focus"
- instance_name: veth
  instance_data_root: data/veth
  instance_prompt: "a picture of [critrole-veth], a female halfling rogue/wizard"
  instance_urls:
  - "https://static.wikia.nocookie.net/criticalrole/images/e/e1/Veth_Level_17_portrait-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/d/dc/Veth_Winter_Headshot.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/f1/Veth_head_portrait_official_2020.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/fc/Veth_full_body_portrait.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/3/3e/Veth-2020.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/93/Veth_Winter.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/9f/Veth_-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/0e/Veth_in_843_PD_by_Zhellers.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/9c/Veth_-_Retrobot3d.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/fa/Veth_-_HeartofPack.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/0d/Veth_-_Ameera.jpg"
  validation_prompt: "a picture of [critrole-veth], a female halfling rogue/wizard. background is a forest. fantasy art style, high quality, highly detailed, sharp focus"
- instance_name: yasha
  instance_data_root: data/yasha
  instance_prompt: "a picture of [critrole-yasha], a female aasimar barbarian"
  instance_urls:
  - "https://static.wikia.nocookie.net/criticalrole/images/d/dd/Yasha_Level_20_portrait_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/3/36/Yasha_Level_17_portrait_-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/4/4c/Yasha_Winter_Headshot.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/6/66/Yashaportrait2019.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/92/Yasha.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/6/6f/Yasha_Official_byArianaOrner.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/ff/Yasha_by_Ariana_Orner.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/f8/Yasha_Winter.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/c/c4/Yasha_Level_20_-_Hannah_Friederichs.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/f5/IMG_20180729_133401.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/6/67/Yasha_jolyneart.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/5/54/IMG_20180729_161237.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/5/5e/Yasha_Tyrone_Andersen.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/a/aa/Yasha_-_Linda_Lithen.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/1/16/Yasha_wombywoo.jpeg"
  - "https://static.wikia.nocookie.net/criticalrole/images/7/7c/Yasha_-_Robson_Michel.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/7/7d/Yasha_AnnaSassiArt.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/0a/Yasha_portrait_-_Ameera.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/4/45/Yasha_-_Ari.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/0/0c/Yasha_playing_her_harp_-_HeartofPack.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/6/68/Yasha_-_Elliott.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/6/6e/Tuskborn_breastplate_casu.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/94/Tumblr_p94nbjxY3P1xqlrkdo1_1280.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/f/fa/Yasha_ambikyu.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/8/8f/Yasha_-_Disarmonia.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/9/95/Joanna-johnen-yasha-wings-sm.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/2/2c/Critical_role_yasha_by_atutcha-dc0iuov-1.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/8/81/Yasha%27s_tattoo_-_BlackSalander.jpg"
  validation_prompt: "a picture of [critrole-yasha], a female aasimar barbarian. background is a forest. fantasy art style, high quality, highly detailed, sharp focus"
- instance_name: mollymauk
  instance_data_root: data/mollymauk
  instance_prompt: "a picture of [critrole-mollymauk], a male tiefling blood hunter"
  instance_urls:
  - "https://static.wikia.nocookie.net/criticalrole/images/c/ce/Mollymauk.jpg"
  - "https://static.wikia.nocookie.net/criticalrole/images/5/51/Mollymauk_Official_byArianaOrner.png"
  - "https://static.wikia.nocookie.net/criticalrole/images/3/35/Lucien_by_Yettinim.jpg"
  validation_prompt: "a picture of [critrole-mollymauk], a male tiefling blood hunter. background is a forest. fantasy art style, high quality, highly detailed, sharp focus"
